# Generated by Django 5.2.1 on 2025-06-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(verbose_name='Rating'),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies_movie',
        ),
    ]
